# Generated by Django 5.1.4 on 2024-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=12)),
                ('end_date', models.DateTimeField()),
                ('cvc', models.CharField(max_length=7)),
                ('checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
