# Generated by Django 5.1.2 on 2024-12-15 08:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('maxValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('remaining', models.PositiveIntegerField()),
                ('sku', models.CharField(default='all', max_length=10)),
            ],
        ),
    ]
