# Generated by Django 5.1.4 on 2024-12-22 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('percent', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('maxValue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('active', models.BooleanField(blank=True, default=True)),
                ('remaining', models.PositiveIntegerField()),
            ],
        ),
    ]
