# Generated by Django 5.1.4 on 2024-12-20 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='orderStatus',
            new_name='paymentMethod',
        ),
        migrations.AddField(
            model_name='order',
            name='couponID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='coupon.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='dateOrder',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
