# Generated by Django 5.1.4 on 2024-12-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(max_length=200)),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('collections', models.CharField(blank=True, max_length=200)),
                ('tags', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['id', 'slug'], name='product_pro_id_b9e5a0_idx')],
            },
        ),
    ]
