# Generated by Django 5.1.2 on 2024-12-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='noOfSolds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='noOfViews',
            field=models.IntegerField(default=0),
        ),
    ]
